project:
  type: book
  output-dir: docs

execute:
  freeze: auto

lang: pt
language:
  title-block-author-single: "Discente"

book:
  title: "MAT2453"
  site-url: "https://beatrizmilz.github.io/2025-01-MAT2453"
  repo-url: "https://github.com/beatrizmilz/2025-01-MAT2453"
  chapters:
    - text: "PÃ¡gina inicial"
      href: index.qmd
    - href: funcoes.qmd
    - href: funcoes-trig.qmd

page-navigation: true


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    number-depth: 1
    link-external-icon: false
    link-external-newwindow: true

editor: source
code-annotations: hover

author:
  - name: "Beatriz Milz"
    url: "https://www.beamilz.com/"
    email: "milz.bea@gmail.com"
